SET TARGET_DATABASE   = '<% dbsname %>';
SET DEPLOY_SCHEMA     = '<% depname %>';
SET DEPLOY_ROLE_OWNER = '<% depname %>_ROL';
SET APP_ROLE_TYPE_01  = '<% depname %>_R01';
SET APP_ROLE_TYPE_02  = '<% depname %>_R02';
SET SERVICE_NAME      = '<% depname %>_SVC';
SET SERVICE_RUN_USER  = '<% depname %>_USR';
SET SERVICE_RUN_POOL  = '<% depname %>_CPL';
SET SERVICE_RUN_VWHS  = '<% depname %>_VWH';
SET EXT_ACC_INT_NAME  = '<% depname %>_EAI';
SET EXT_ACC_NET_RULE  = '<% depname %>_NRL';


---------------------------------------------------------------------------------
USE ROLE IDENTIFIER($DEPLOY_ROLE_OWNER);
USE DATABASE IDENTIFIER($TARGET_DATABASE);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);
USE WAREHOUSE IDENTIFIER($SERVICE_RUN_VWHS);

LIST @SPECS PATTERN='.*yaml';
REMOVE @SPECS PATTERN='.*yaml';
PUT file://img/service.yaml @SPECS AUTO_COMPRESS=FALSE OVERWRITE=TRUE; 

LIST @VOLUMES PATTERN='.*gz';
REMOVE @VOLUMES PATTERN='.*gz';
PUT file://app.tar.gz @VOLUMES AUTO_COMPRESS=FALSE OVERWRITE=TRUE; 

DESC COMPUTE POOL IDENTIFIER($SERVICE_RUN_POOL);
--ALTER COMPUTE POOL IF EXISTS IDENTIFIER($SERVICE_RUN_POOL) SUSPEND;
ALTER COMPUTE POOL IF EXISTS IDENTIFIER($SERVICE_RUN_POOL) RESUME IF SUSPENDED;

ALTER SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME) SUSPEND;
--ALTER SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME) RESUME;

DROP SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME);
CREATE SERVICE IDENTIFIER($SERVICE_NAME)
  IN COMPUTE POOL IDENTIFIER($SERVICE_RUN_POOL)
  FROM @SPECS
  SPECIFICATION_FILE = 'service.yaml'
  EXTERNAL_ACCESS_INTEGRATIONS = ($EXT_ACC_INT_NAME)
  MIN_INSTANCES = 1
  MAX_INSTANCES = 1
;

SHOW SERVICES;

-- wait for service provisioning to complete
CALL SYSTEM$WAIT(1, 'MINUTES');

-- check the status of service
CALL SYSTEM$GET_SERVICE_STATUS($SERVICE_NAME);
