SET TARGET_DATABASE   = '<% dbsname %>';
SET DEPLOY_SCHEMA     = '<% depname %>';
SET DEPLOY_ROLE_OWNER = 'APP_<% depname %>_OWNER';
SET APP_ROLE_TYPE_01  = 'APP_<% depname %>_ROL01';
SET APP_ROLE_TYPE_02  = 'APP_<% depname %>_ROL02';
SET APP_NB_CONTROL    = 'APP_<% depname %>_CONTROL';
SET SERVICE_NAME      = 'APP_<% depname %>_SVC';
SET SERVICE_RUN_USER  = 'APP_<% depname %>_USER';
SET SERVICE_RUN_POOL  = 'APP_<% depname %>_POOL';
SET SERVICE_RUN_VWHS  = 'APP_<% depname %>_WH';
SET EXT_ACC_INT_NAME  = 'APP_<% depname %>_EXASINT';
SET EXT_ACC_NET_RULE  = 'APP_<% depname %>_NETRULE';


---------------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
USE DATABASE IDENTIFIER($TARGET_DATABASE);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($DEPLOY_SCHEMA);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);

DROP USER IF EXISTS IDENTIFIER($SERVICE_RUN_USER);
DROP ROLE IF EXISTS IDENTIFIER($DEPLOY_ROLE_OWNER);
DROP ROLE IF EXISTS IDENTIFIER($APP_ROLE_TYPE_01);

DROP NOTEBOOK IF EXISTS IDENTIFIER($APP_NB_CONTROL);

ALTER SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME) SUSPEND;
DROP SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME) FORCE;

ALTER COMPUTE POOL IF EXISTS IDENTIFIER($SERVICE_RUN_POOL) SUSPEND;
DROP COMPUTE POOL IF EXISTS IDENTIFIER($SERVICE_RUN_POOL);

DROP WAREHOUSE IF EXISTS IDENTIFIER($SERVICE_RUN_VWHS);

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS IDENTIFIER($EXT_ACC_INT_NAME);
DROP NETWORK RULE IF EXISTS IDENTIFIER($EXT_ACC_NET_RULE);

DROP SCHEMA IF EXISTS IDENTIFIER($DEPLOY_SCHEMA);
