SET TARGET_DATABASE   = '<% dbsname %>';
SET DEPLOY_SCHEMA     = '<% depname %>';
SET DEPLOY_ROLE_OWNER = '<% depname %>_ROL';
SET APP_ROLE_TYPE_01  = '<% depname %>_R01';
SET APP_ROLE_TYPE_02  = '<% depname %>_R02';
SET SERVICE_NAME      = '<% depname %>_SVC';
SET SERVICE_RUN_USER  = '<% depname %>_USR';
SET SERVICE_RUN_POOL  = '<% depname %>_CPL';
SET SERVICE_RUN_VWHS  = '<% depname %>_VWH';
SET EXT_ACC_INT_NAME  = '<% depname %>_EAI';
SET EXT_ACC_NET_RULE  = '<% depname %>_NRL';


---------------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
USE DATABASE IDENTIFIER($TARGET_DATABASE);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($DEPLOY_SCHEMA);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);

DROP USER IF EXISTS IDENTIFIER($SERVICE_RUN_USER);
DROP ROLE IF EXISTS IDENTIFIER($DEPLOY_ROLE_OWNER);

ALTER SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME) SUSPEND;
DROP SERVICE IF EXISTS IDENTIFIER($SERVICE_NAME);

ALTER COMPUTE POOL IF EXISTS IDENTIFIER($SERVICE_RUN_POOL) SUSPEND;
DROP COMPUTE POOL IF EXISTS IDENTIFIER($SERVICE_RUN_POOL);

DROP WAREHOUSE IF EXISTS IDENTIFIER($SERVICE_RUN_VWHS);

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS IDENTIFIER($EXT_ACC_INT_NAME);
DROP NETWORK RULE IF EXISTS IDENTIFIER($EXT_ACC_NET_RULE);

DROP SCHEMA IF EXISTS IDENTIFIER($DEPLOY_SCHEMA);
